### ISSUE TITLE
Analisar bibliotecas de NLP (Natural Language Processing)

### ISSUE THREAD

**Issue by 7robertodantas** [devfest-ufrn/piggy-bot#2]
- http://www.nltk.org/
- https://wit.ai
- https://dialogflow.com/

**Comment by PCoelho07** [comment]
Uma breve introdução da dialogflow(antiga *api.ai*).
https://medium.com/botsbrasil/api-ai-breve-introdu%C3%A7%C3%A3o-da-plataforma-ecb2d77107a2

**Comment by 7robertodantas** [comment]
Optamos por utilizar DialogFlow
